apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  mysql-db-name: db_zenblog

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  mysql-user: cm9vdA==
  mysql-password: cm9vdDEyMw==
  redis-password: cm9vdDEyMw==

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: "mysql"
  selector:
    matchLabels:
      app: mysql
      tier: mysql
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: mysql-db-name
            - name: MYSQL_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-user
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-password
          volumeMounts:
            - mountPath: /var/lib/mysql #/bitnami/mysql/data
              name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mysql
