apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: example-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-server.example.com
  share: /srv/nfs/kubedata/storage
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - hard
  - nfsvers=4.1

#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: web-server-pv
#spec:
#  storageClassName: "example-nfs"
#  capacity:
#    storage: 10Gi
#  persistentVolumeReclaimPolicy: Retain
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "example-nfs"
  resources:
    requests:
      storage: 1Gi
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql-pvc
#spec:
#  accessModes:
#    - ReadWriteMany
#  storageClassName: "example-nfs"
#  resources:
#    requests:
#      storage: 5Gi
#
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: nginx-claim
#  labels:
#    name: nginx-pvc
#spec:
#  storageClassName: example-nfs
#  volumeName: web-server-volume
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 1Gi

#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: web-server-pv
#spec:
#  capacity:
#    storage: 10Gi
#  accessModes:
#    - ReadWriteMany
#  nfs:
#    server: nfs-server.example.com
#    path: "/srv/nfs/kubedata/storage"
#  mountOptions:
#    - nfsvers=4.1
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: nginx-pvc
#spec:
#  accessModes:
#    - ReadWriteMany
#  storageClassName: ""
#  resources:
#    requests:
#      storage: 1Gi
#  volumeName: web-server-pv

#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: nfs-web
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      role: web-frontend
#  template:
#    metadata:
#      labels:
#        role: web-frontend
#    spec:
#      containers:
#        - name: web
#          image: nginx
#          ports:
#            - name: web
#              containerPort: 80
#          volumeMounts:
#            # name must match the volume name below
#            - name: html-folder
#              mountPath: "/usr/share/nginx/html"
#      volumes:
#        - name: html-folder
#          persistentVolumeClaim:
#            claimName: nginx-pvc

#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: db-server-pv
#spec:
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  nfs:
#    path: /srv/nfs/kubedata/storage
#    server: nfs-server.example.com
#  persistentVolumeReclaimPolicy: Delete
#  claimRef:
#     name: mysql-pvc
#     namespace: default
#
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi